package cn.edu.gdut.llc.mybatis.model;

import java.util.Date;

public class Login {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.id
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.phone
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.mail
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.username
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.password
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.state
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.role
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.create_time
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.last_login_time
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.ip_add
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private String ipAdd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.id
     *
     * @return the value of login.id
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.id
     *
     * @param id the value for login.id
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.phone
     *
     * @return the value of login.phone
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.phone
     *
     * @param phone the value for login.phone
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.mail
     *
     * @return the value of login.mail
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.mail
     *
     * @param mail the value for login.mail
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.username
     *
     * @return the value of login.username
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.username
     *
     * @param username the value for login.username
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.password
     *
     * @return the value of login.password
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.password
     *
     * @param password the value for login.password
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.state
     *
     * @return the value of login.state
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.state
     *
     * @param state the value for login.state
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.role
     *
     * @return the value of login.role
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.role
     *
     * @param role the value for login.role
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.create_time
     *
     * @return the value of login.create_time
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.create_time
     *
     * @param createTime the value for login.create_time
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.last_login_time
     *
     * @return the value of login.last_login_time
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.last_login_time
     *
     * @param lastLoginTime the value for login.last_login_time
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.ip_add
     *
     * @return the value of login.ip_add
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public String getIpAdd() {
        return ipAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.ip_add
     *
     * @param ipAdd the value for login.ip_add
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setIpAdd(String ipAdd) {
        this.ipAdd = ipAdd == null ? null : ipAdd.trim();
    }
}