package cn.edu.gdut.llc.mybatis.model;

import java.util.Date;

public class Weixin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin.openid
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin.username
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin.nickname
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin.sex
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin.country
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin.province
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin.city
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin.head_img_url
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private String headImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin.bind_time
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    private Date bindTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin.openid
     *
     * @return the value of weixin.openid
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin.openid
     *
     * @param openid the value for weixin.openid
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin.username
     *
     * @return the value of weixin.username
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin.username
     *
     * @param username the value for weixin.username
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin.nickname
     *
     * @return the value of weixin.nickname
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin.nickname
     *
     * @param nickname the value for weixin.nickname
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin.sex
     *
     * @return the value of weixin.sex
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin.sex
     *
     * @param sex the value for weixin.sex
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin.country
     *
     * @return the value of weixin.country
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin.country
     *
     * @param country the value for weixin.country
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin.province
     *
     * @return the value of weixin.province
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin.province
     *
     * @param province the value for weixin.province
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin.city
     *
     * @return the value of weixin.city
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin.city
     *
     * @param city the value for weixin.city
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin.head_img_url
     *
     * @return the value of weixin.head_img_url
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public String getHeadImgUrl() {
        return headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin.head_img_url
     *
     * @param headImgUrl the value for weixin.head_img_url
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl == null ? null : headImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin.bind_time
     *
     * @return the value of weixin.bind_time
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public Date getBindTime() {
        return bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin.bind_time
     *
     * @param bindTime the value for weixin.bind_time
     *
     * @mbggenerated Wed Jul 27 09:29:22 CST 2016
     */
    public void setBindTime(Date bindTime) {
        this.bindTime = bindTime;
    }
}